### ISSUE TITLE
Form isn't clear on mobile

### ISSUE THREAD

**Issue by sumukhshetty** [joshpitzalis/bunch#10]
<img width="405" alt="Screenshot 2020-04-24 at 11 17 10 AM" src="https://user-images.githubusercontent.com/22879373/80178991-33d51e80-861d-11ea-9aba-321092d7faf2.png">

Amt and value don't show up so I'm not sure what info I should add there if I start out on mobile.

**Comment by joshpitzalis** [comment]
54265d8915037f5ffc898137403e87aa1dea3435
