### ISSUE TITLE
Link to menu not showing up properly 

### ISSUE THREAD

**Issue by sumukhshetty** [joshpitzalis/bunch#5]
<img width="1421" alt="Screenshot 2020-04-24 at 10 59 17 AM" src="https://user-images.githubusercontent.com/22879373/80178137-2dde3e00-861b-11ea-9176-d892845728a6.png">

**Comment by sumukhshetty** [comment]
On mobile 
<img width="413" alt="Screenshot 2020-04-24 at 11 25 22 AM" src="https://user-images.githubusercontent.com/22879373/80179509-5a478980-861e-11ea-9426-999d4cbdc54e.png">

**Comment by joshpitzalis** [comment]
05fb77c1332c627f9bb51122ef4b3fc5ec2c8ae2
